#!/bin/bash

calendarl() {
    LOCK_FILE_CALENDAR="$HOME/.cache/eww-calendar.lock"

run() {
    eww open calendar -c ~/.config/polybar/widgets/
}

# Open widgets
if [[ ! -f "$LOCK_FILE_CALENDAR" ]]; then
    eww close calendar -c ~/.config/polybar/widgets/
    touch "$LOCK_FILE_CALENDAR"
    run && echo "ok good!"
elif [[ -f "$LOCK_FILE_CALENDAR" ]]; then
    eww close calendar -c ~/.config/polybar/widgets/
    rm "$LOCK_FILE_CALENDAR" && echo "closed"
fi
}

calendarl

